Adds a FAQ section with an image on the left hand side
life-efficient/Conversationally pull request #81
Opened 2023-12-16 18:26 UTC by lizzietm

Adds a FAQ section with an image on the left hand side (works for website, not sure if image shows above FAQs on mobile so need someone to check.)

2023-12-16 23:21 UTC, life-efficient requested changes

2023-12-16 23:21 UTC, life-efficient commented on conversationally/frontend/src/pages/landingPage/LandingPage.jsx
> +import FAQs from "./sections/FAQs.jsx"
No need for file extensions when it's a JSX import (usually a component)

2023-12-16 23:21 UTC, life-efficient commented on conversationally/frontend/src/pages/landingPage/LandingPage.jsx
> +            <FAQs img='conversationally/frontend/public/wav.png' faqs={faqData} />
The "fold" is defined as the part of the website you see when you first land on it, so naturally it has to come first (after the navbar)

2023-12-16 23:21 UTC, life-efficient commented on conversationally/frontend/src/pages/landingPage/sections/FAQs.jsx
> +              <Typography>{faq.question}</Typography>
Always supply a variant prop to the typography component

2023-12-16 23:22 UTC, life-efficient commented
- [ ] Also, please generate a better image that could realistically be used here. The one you've got is not good enough.

2023-12-17 00:26 UTC, life-efficient commented
Closes #78

2023-12-17 05:20 UTC, lizzietm commented on conversationally/frontend/src/pages/landingPage/LandingPage.jsx
> +            <FAQs img='conversationally/frontend/public/wav.png' faqs={faqData} />
"fold" replaced back into it's original position.

2023-12-17 06:19 UTC, lizzietm commented on conversationally/frontend/src/pages/landingPage/LandingPage.jsx
> +import FAQs from "./sections/FAQs.jsx"
Extension removed.

2023-12-17 06:35 UTC, lizzietm commented on conversationally/frontend/src/pages/landingPage/sections/FAQs.jsx
> +              <Typography>{faq.question}</Typography>
Added a h7 variant prop.

2023-12-17 23:57 UTC, lizzietm reviewed
FAQ section still has scaling issue for mobile and web but requesting to merge to find all the issues in the MVP

2023-12-18 00:36 UTC, merged