Testimonials
life-efficient/Conversationally pull request #91
Opened 2023-12-17 20:28 UTC by lizzietm

Added a testimonials section for the landing page.  Which should be responsive for computer and mobile devices

2023-12-17 21:00 UTC, life-efficient requested changes

2023-12-17 21:00 UTC, life-efficient commented on conversationally/frontend/src/pages/landingPage/sections/Testimonials.jsx
> +        margin: theme.spacing(1),
This seems unnecessary

2023-12-18 00:01 UTC, lizzietm commented on conversationally/frontend/src/pages/landingPage/sections/Testimonials.jsx
> +        margin: theme.spacing(1),
Unecessary lines removed.

2023-12-18 00:02 UTC, lizzietm commented on conversationally/frontend/src/pages/landingPage/LandingPage.jsx
> +    },
Will do and will make the changes.

2023-12-18 00:04 UTC, lizzietm commented on conversationally/frontend/src/pages/landingPage/sections/Testimonials.jsx
> +                    </DemoPaper>
Going to merge for the MVP and then work on this in the background.

2023-12-18 00:04 UTC, lizzietm commented on conversationally/frontend/src/pages/landingPage/sections/Testimonials.jsx
> +const DemoPaper = styled(Paper)(({ theme }) => (
Going to merge for the MVP and then work on this in the background.

2023-12-18 00:08 UTC, lizzietm reviewed
Going to merge for the MVP and then work on this in the background.

2023-12-18 00:11 UTC, merged